### ISSUE TITLE
50k log file does not load

### ISSUE THREAD

**Issue by jaxxstorm** [adragomir/hubot-logger#5]
I'm using the hubot-logger on a logfile of around 50k from yesterday, and it doesn't seem to be able to load the page. Is there any debugging I can enable that can determine why?

**Comment by jaxxstorm** [comment]
The error thrown is here: 

```
ERROR TypeError: Cannot call method 'getTimezoneOffset' of undefined
  at Tempus.setTimezoneToLocale (/opt/opsbot/node_modules/hubot-logger/node_modules/Tempus/tempus.js:538:45)
  at Tempus.set (/opt/opsbot/node_modules/hubot-logger/node_modules/Tempus/tempus.js:263:18)
  at new Tempus (/opt/opsbot/node_modules/hubot-logger/node_modules/Tempus/tempus.js:34:18)
  at parse_events (/opt/opsbot/node_modules/hubot-logger/scripts/hubot-logger.coffee:70:7, <js>:74:22)
  at ReadStream.<anonymous> (/opt/opsbot/node_modules/hubot-logger/scripts/hubot-logger.coffee:87:5, <js>:94:7)
  at ReadStream.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:919:16
  at process._tickCallback (node.js:419:13)
```

It looks like the issue might be caused by this: https://github.com/adragomir/hubot-logger/blob/master/scripts/hubot-logger.coffee#L86

But I don't know enough JS/coffeescript to debug it

**Comment by wamaral** [comment]
The file size is not the problem here, I traced back the error to the way the Tempus library is storing timestamps close to midnight. Here is an example:

The following entry was generated on 23:35:58 at GMT-3, however it is stored as -1:35:58 (i.e. 1 hour until midnight)

`{"nick":"AndreSenaubar","reason":"Ping timeout: 20 seconds","date":"2015-03-12T-1:35:58.049-0300","channel":"#musashi","type":"quit"}`

For me, since I am on GMT-3, it affects all entries generated between 21:00:00 and 23:59:59

Here is an entry from the same logfile, before 9pm, generated correctly:

`{"nick":"jenkins-musashi","reason":"Ping timeout: 20 seconds","date":"2015-03-12T20:50:31.521-0300","channel":"#musashi","type":"quit"}`

Note how the time was stored correctly as 20:50:31, because it is more than 3 hours from GMT

I see the development of the Tempus library is halted and the author is not accepting pull requests, so I would advise @adragomir to consider switching libraries
